# -*- conf -*-
# Foot terminal configuration

term=foot
font=Iosevka Nerd Font Mono:size=16
pad=8x8 center

[cursor]
style=block

[mouse]
hide-when-typing=yes

[colors-dark]
alpha=0.85

[main]
include=/home/megha/.local/share/tinted-theming/tinty/artifacts/tinted-foot-colors-file.ini
