[ids]
*

[main]
# Maps CapsLock to Hyper (Ctrl+Alt+Shift+Super) when held, and Escape when tapped
capslock = overload(hyper, esc)

# Custom hyper layer (Control + Alt + Shift + Meta/Super)
[hyper:C-A-S-M]
